services:
  magma-core:
    build:
      context: .
      dockerfile: core/Dockerfile
    container_name: magma-core
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:sqlite.db
      - JWT_SECRET=${JWT_SECRET:-magma-secret-prod-12345}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-default-encryption-key-32-chars-long}
#      - ENCRYPTION_KEY=f30d098f6b4d3a2e1c0b9a87766554433221100f8e7d6c5b4a39281706152433
    volumes:
      - ./core/sqlite.db:/home/node/app/sqlite.db
      - ./storage:/home/node/app/storage
    networks:
      - magma-network

  magma-app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: magma-app
    restart: always
    environment:
      - VITE_SERVICE_URL=/
      - CORE_HOST=${CORE_HOST:-magma-core}
      - NGINX_ENVSUBST_FILTER=CORE_HOST
    ports:
      - "80:80"
    depends_on:
      - magma-core
    networks:
      - magma-network

networks:
  magma-network:
    driver: bridge
