import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./generated/schema"; // Autogenerated types
import { AppConfig } from "../../config/app.config";
import { useAuthStore } from "../../store/authStore";

/**
 * Magma API Client
 * 
 * Centralized API client with automatic headers and error interception.
 */
export const api = createClient<paths>({
  baseUrl: AppConfig.serviceUrl,
});

/**
 * Auth Middleware
 * 
 * Automatically attaches the Bearer token to all requests if it exists in the store.
 * Also intercepts 401 errors to trigger logout and redirect.
 */
const authMiddleware: Middleware = {
  // eslint-disable-next-line @typescript-eslint/require-await
  async onRequest({ request }) {
    const { token } = useAuthStore.getState();
    if (token) {
      request.headers.set("Authorization", `Bearer ${token}`);
    }
    return request;
  },
  async onResponse({ response }) {
    if (response.status === 401) {
      console.warn("[API] 401 Unauthorized detected. Clearing session.");
      useAuthStore.getState().logout();
      // Forward redirection logic is handled by ProtectedRoute or app state reaction
    }
    return response;
  }
};

// Register middleware
api.use(authMiddleware);
