import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./generated/schema"; // Autogenerated types
import { AppConfig } from "../../config/app.config";
import { useAuthStore } from "../../store/authStore";

/**
 * Magma API Client
 * 
 * Centralized API client with automatic headers and error interception.
 */
export const api = createClient<paths>({
  baseUrl: AppConfig.serviceUrl,
});

// To handle multiple simultaneous 401s, we use a single flight refresh strategy.
// All concurrent 401s will wait for this promise.
let refreshPromise: Promise<string | null> | null = null;

/**
 * Auth Middleware
 * 
 * Automatically attaches the Bearer token to all requests if it exists in the store.
 * Also intercepts 401 errors to trigger logout and redirect.
 */
const authMiddleware: Middleware = {
  // eslint-disable-next-line @typescript-eslint/require-await
  async onRequest({ request }) {
    const { token } = useAuthStore.getState();
    if (token) {
      request.headers.set("Authorization", `Bearer ${token}`);
    }
    return request;
  },
  async onResponse({ response, request }) {
    // If 401 and we have a refresh token, try to refresh
    if (response.status === 401) {
      const { refreshToken, updateAccessToken, logout } = useAuthStore.getState();

      // Avoid infinite loop if refreshing fails
      if (request.url.includes("/auth/refresh")) {
        console.error("[API] Refresh failed. Logging out.");
        logout();
        return response;
      }

      if (refreshToken) {
        try {
          // Check if we already have a refresh in progress
          if (!refreshPromise) {
            console.log("[API] 401 detected. Initiating single-flight token refresh...");
            refreshPromise = (async () => {
              try {
                const refreshRes = await fetch(`${AppConfig.serviceUrl}/api/v1/auth/refresh`, {
                  method: "POST",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({ refreshToken }),
                });

                if (refreshRes.ok) {
                  const data = await refreshRes.json();
                  console.log("[API] Token refreshed successfully.");
                  updateAccessToken(data.accessToken, data.refreshToken);
                  return data.accessToken;
                }
                return null;
              } catch (err) {
                console.error("[API] Error inside refresh promise:", err);
                return null;
              } finally {
                // Important: Reset the promise so future refreshes can happen
                refreshPromise = null;
              }
            })();
          } else {
            console.log("[API] 401 detected. Waiting for existing refresh promise...");
          }

          const newAccessToken = await refreshPromise;

          if (newAccessToken) {
            // Retry the original request with the new token
            const newRequest = new Request(request.url, request);
            newRequest.headers.set("Authorization", `Bearer ${newAccessToken}`);
            return fetch(newRequest);
          } else {
            console.warn("[API] Refresh attempt failed or returned null.");
            logout();
          }
        } catch (err) {
          console.error("[API] Error during refresh management:", err);
          logout();
        }
      } else {
        console.warn("[API] 401 Unauthorized detected and no refresh token available.");
        logout();
      }
    }
    return response;
  }
};

// Register middleware
api.use(authMiddleware);
