import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "./generated/schema"; // Autogenerated types
import { AppConfig } from "../../config/app.config";
import { useAuthStore } from "../../store/authStore";

/**
 * Magma API Client
 * 
 * Centralized API client with automatic headers and error interception.
 */
export const api = createClient<paths>({
  baseUrl: AppConfig.serviceUrl,
});

/**
 * Auth Middleware
 * 
 * Automatically attaches the Bearer token to all requests if it exists in the store.
 * Also intercepts 401 errors to trigger logout and redirect.
 */
const authMiddleware: Middleware = {
  // eslint-disable-next-line @typescript-eslint/require-await
  async onRequest({ request }) {
    const { token } = useAuthStore.getState();
    if (token) {
      request.headers.set("Authorization", `Bearer ${token}`);
    }
    return request;
  },
  async onResponse({ response, request }) {
    // If 401 and we have a refresh token, try to refresh
    if (response.status === 401) {
      const { refreshToken, updateAccessToken, logout } = useAuthStore.getState();

      // Avoid infinite loop if refreshing fails
      if (request.url.includes("/auth/refresh")) {
        console.error("[API] Refresh failed. Logging out.");
        logout();
        return response;
      }

      if (refreshToken) {
        console.log("[API] 401 detected. Attempting token refresh...");
        try {
          // We use fetch directly to avoid triggering the middleware recursively here
          const refreshRes = await fetch(`${AppConfig.serviceUrl}/api/v1/auth/refresh`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ refreshToken }),
          });

          if (refreshRes.ok) {
            const data = await refreshRes.json();
            console.log("[API] Token refreshed successfully.");
            updateAccessToken(data.accessToken, data.refreshToken);

            // Retry the original request with the new token
            const newRequest = new Request(request.url, request);
            newRequest.headers.set("Authorization", `Bearer ${data.accessToken}`);
            return fetch(newRequest);
          } else {
            console.warn("[API] Refresh token invalid or expired.");
            logout();
          }
        } catch (err) {
          console.error("[API] Error during refresh attempt:", err);
          logout();
        }
      } else {
        console.warn("[API] 401 Unauthorized detected and no refresh token available.");
        logout();
      }
    }
    return response;
  }
};

// Register middleware
api.use(authMiddleware);
