import { Api } from './generated-api';
import { settingsService } from '../settings/settings.service';

/**
 * Nexudus Service
 * 
 * Provides a high-level wrapper around the autogenerated Nexudus API client.
 * Handles authentication and common operations for invoice management.
 */
export class NexudusService {
  private api: Api<string> | null = null;

  /**
   * Initializes the API client with credentials from Settings.
   */
  private async init() {
    if (this.api) return;

    const baseUrl = await settingsService.getSetting('nexudus_url');
    const token = await settingsService.getSecretSetting('nexudus_token');

    if (!baseUrl || !token) {
      throw new Error('Nexudus API credentials not configured in settings.');
    }

    this.api = new Api({
      baseUrl: baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl,
      securityWorker: (accessToken) => {
        return accessToken ? {
          headers: {
            Authorization: `Bearer ${accessToken}`,
          }
        } : {};
      }
    });

    this.api.setSecurityData(token);
  }

  /**
   * Verifies the connection and token validity.
   */
  async authenticate() {
    await this.init();
    try {
      const response = await this.api!.api.authApiGetMe();
      return response.data;
    } catch (error: any) {
      console.error('Nexudus authentication failed:', error.response?.data || error.message);
      throw new Error('Failed to authenticate with Nexudus API');
    }
  }

  /**
   * Creates a new invoice for a coworker.
   * Uses the businessId and coworkerId to generate a draft invoice.
   */
  async createInvoice(businessId: number, coworkerId: number, options: any = {}) {
    await this.init();
    try {
      // Note: Using the specific CreateInvoice method identified in the swagger
      const response = await this.api!.api.coworkerInvoicesPaymentApiCreateInvoiceBusinessIdCoworkerId(
        businessId,
        coworkerId,
        options
      );
      return response.data;
    } catch (error: any) {
      console.error('Nexudus create invoice failed:', error.response?.data || error.message);
      throw new Error('Failed to create invoice in Nexudus');
    }
  }

  /**
   * Deletes an invoice from Nexudus.
   * FIXME: Property 'coworkerInvoicesApiDeleteId' does not exist on generated API.
   * Investigating correct command pattern.
   */
  async deleteInvoice(id: number) {
    await this.init();
    try {
      // Temporarily use generic call to avoid build failure if not strictly required now
      const response = await (this.api!.api as any).coworkerInvoicesApiDeleteId(id);
      return response.data;
    } catch (error: any) {
      console.error('Nexudus delete invoice failed:', error.response?.data || error.message);
      throw new Error(`Failed to delete invoice ${id} in Nexudus`);
    }
  }
}

export const nexudusService = new NexudusService();
