import { Api, ContentType, NexudusCoworkingCoreQueryDtosBillingCoworkerProductDto } from './generated-api';
import { settingsService } from '../settings/settings.service';
import { logger } from '../../lib/logger';

/**
 * Nexudus Service
 * 
 * Provides a high-level wrapper around the autogenerated Nexudus API client.
 * Handles authentication and common operations for consumption management.
 */
export class NexudusService {
  private api: Api<string> | null = null;
  private token: string | null = null;

  /**
   * Initializes the API client with credentials from Settings.
   * If no token is found or valid, attempts to login.
   */
  private async init() {
    if (this.api && this.token) return;

    const baseUrl = await settingsService.getSetting('nexudus_url');
    this.token = await settingsService.getSecretSetting('nexudus_token');

    if (!baseUrl) {
      throw new Error('Nexudus API URL not configured in settings.');
    }

    this.api = new Api({
      baseUrl: baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl,
      securityWorker: (accessToken) => {
        return accessToken ? {
          headers: {
            Authorization: `Bearer ${accessToken}`,
          }
        } : {};
      }
    });

    if (!this.token) {
      await this.login();
    } else {
      this.api.setSecurityData(this.token);
    }
  }

  /**
   * Performs login to Nexudus to obtain a temporary token.
   */
  async login() {
    const baseUrl = await settingsService.getSetting('nexudus_url');
    const email = await settingsService.getSetting('nexudus_email');
    const password = await settingsService.getSecretSetting('nexudus_password');

    if (!email || !password) {
      throw new Error('Nexudus email or password not configured in settings.');
    }

    if (!this.api) {
      this.api = new Api({
        baseUrl: baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl,
      });
    }

    try {
      const response = await this.api.api.usersApiToken({
        Email: email,
        Password: password,
      });

      if (response.data.WasSuccessful && response.data.Value) {
        this.token = response.data.Value as unknown as string;
        this.api.setSecurityData(this.token);
        
        // Persist the token for future requests (temporary storage in settings)
        await settingsService.updateSetting('nexudus_token', this.token);
        return this.token;
      } else {
        throw new Error(response.data.Message || 'Login failed without message');
      }
    } catch (error: any) {
      logger.error({ error: error.response?.data || error.message }, 'Nexudus: Login failed');
      throw new Error('Failed to login to Nexudus API');
    }
  }

  /**
   * Verifies the connection and token validity.
   */
  async authenticate() {
    await this.init();
    try {
      const response = await this.api!.api.authApiGetMe();
      return response.data;
    } catch (error: any) {
      // If unauthorized, try to relogin once
      if (error.response?.status === 401) {
        await this.login();
        const retryResponse = await this.api!.api.authApiGetMe();
        return retryResponse.data;
      }
      logger.error({ error: error.response?.data || error.message }, 'Nexudus: Authentication failed');
      throw new Error('Failed to authenticate with Nexudus API');
    }
  }

  /**
   * Registers a product sale (CoworkerProduct) in Nexudus.
   * This is the preferred way to "bill" consumption.
   */
  async createCoworkerProduct(data: NexudusCoworkingCoreQueryDtosBillingCoworkerProductDto) {
    await this.init();
    try {
      const response = await this.api!.api.coworkerProductsApiPost(data);
      if (response.data.WasSuccessful) {
        return response.data;
      } else {
        throw new Error(response.data.Message || 'Failed to create coworker product');
      }
    } catch (error: any) {
      // Handle session expiration
      if (error.response?.status === 401) {
        await this.login();
        const retryResponse = await this.api!.api.coworkerProductsApiPost(data);
        return retryResponse.data;
      }
      logger.error({ error: error.response?.data || error.message }, 'Nexudus: Create coworker product failed');
      throw new Error('Failed to create coworker product in Nexudus');
    }
  }

  /**
   * Creates a new invoice for a coworker (Draft).
   */
  async createInvoice(businessId: number, coworkerId: number, options: any = {}) {
    await this.init();
    try {
      const response = await this.api!.api.coworkerInvoicesPaymentApiCreateInvoiceBusinessIdCoworkerId(
        businessId,
        coworkerId,
        options
      );
      return response.data;
    } catch (error: any) {
      if (error.response?.status === 401) {
        await this.login();
        // retry...
      }
      logger.error({ error: error.response?.data || error.message }, 'Nexudus: Create invoice failed');
      throw new Error('Failed to create invoice in Nexudus');
    }
  }

  /**
   * Deletes an invoice from Nexudus.
   */
  async deleteInvoice(id: number) {
    await this.init();
    try {
      const response = await (this.api!.api as any).coworkerInvoicesApiDeleteId(id);
      return response.data;
    } catch (error: any) {
      logger.error({ error: error.response?.data || error.message, id }, 'Nexudus: Delete invoice failed');
      throw new Error(`Failed to delete invoice ${id} in Nexudus`);
    }
  }
}

export const nexudusService = new NexudusService();
