name: Docker Hub Publish

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Core
        id: meta-core
        uses: docker/metadata-action@v5
        with:
          images: oottee/ote
          tags: |
            type=ref,event=branch,prefix=magma-core-
            type=semver,pattern=magma-core-{{version}}
            type=sha,format=short,prefix=magma-core-

      - name: Build and push Core
        uses: docker/build-push-action@v5
        with:
          context: .
          file: core/Dockerfile
          push: true
          tags: ${{ steps.meta-core.outputs.tags }}
          labels: ${{ steps.meta-core.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata (tags, labels) for App
        id: meta-app
        uses: docker/metadata-action@v5
        with:
          images: oottee/ote
          tags: |
            type=ref,event=branch,prefix=magma-app-
            type=semver,pattern=magma-app-{{version}}
            type=sha,format=short,prefix=magma-app-

      - name: Build and push App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: app/Dockerfile
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
